name: horovod_test
channels:
- conda-forge
- defaults
- nvidia
dependencies:
- jupyterlab=3.2.2
- libgcc=7.2.0
- nccl=2.11.4.1
- pandas=1.3.3
- cudatoolkit=11.4
- pip=21.3
- pip:
  - absl-py==0.15.0
  - astunparse==1.6.3
  - cachetools==4.2.4
  - certifi==2021.10.8
  - cffi==1.15.0
  - charset-normalizer==2.0.7
  - cloudpickle==2.0.0
  - cycler==0.11.0
  - flatbuffers==1.12
  - fonttools==4.32.0
  - gast==0.3.3
  - google-auth==2.3.0
  - google-auth-oauthlib==0.4.6
  - google-pasta==0.2.0
  - grpcio==1.32.0
  - h5py==2.10.0
  - horovod==0.23.0
  - idna==3.3
  - keras-preprocessing==1.1.2
  - kiwisolver==1.4.2
  - llvmlite==0.37.0
  - markdown==3.3.4
  - matplotlib==3.5.1
  - numba==0.54.1
  - numpy==1.19.5
  - oauthlib==3.1.1
  - opt-einsum==3.3.0
  - pillow==8.4.0
  - protobuf==3.18.1
  - psutil==5.8.0
  - pyasn1==0.4.8
  - pyasn1-modules==0.2.8
  - pyyaml==6.0
  - requests-oauthlib==1.3.0
  - rsa==4.7.2
  - scipy==1.7.1
  - six==1.15.0
  - tensorboard==2.7.0
  - tensorboard-data-server==0.6.1
  - tensorboard-plugin-wit==1.8.0
  - tensorflow-estimator==2.4.0
  - tensorflow-gpu==2.4.1
  - termcolor==1.1.0
  - torch==1.9.1+cu111
  - torch-summary==1.4.5
  - torchaudio==0.9.1
  - torchvision==0.10.1+cu111
  - typing-extensions==3.7.4.3
  - werkzeug==2.0.2
  - wrapt==1.12.1
