module @LogregTorchSamba.partition_1_0_.logreg__criterion__crossentropyloss_bwd_loss  {
  module @tcompute0  {
    "rail.tcompute"() ( {
      "rail.tcompute_context"() ( {
        %7 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 0 : i64} : () -> i64
        %8 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 32 : i64} : () -> i64
        %9 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 1 : i64} : () -> i64
        %10 = "rail.iterator"(%7, %8, %9) {Par = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64, i64, i64) -> i64
        %11 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64) -> i1
        %12 = "rail.ctxdone"(%11) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i1) -> i1
        %13 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 0 : i64} : () -> i64
        %14 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 1 : i64} : () -> i64
        %15 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 12 : i64} : () -> i64
        %16 = "rail.iterator"(%13, %14, %15) {Par = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64, i64, i64) -> i64
        %17 = "rail.io.vector_in"() {kCtxName = "phase0", kLanes = [], kPortName = "0", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", kVectorLengthInBytes = 64 : i64, sym_name = "tcompute0_tcompute_phase0_vector_in_0"} : () -> vector<32xbf16>
        %18 = "rail.io.vector_out"() {kCtxName = "phase0", kLanes = [], kPortName = "2000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", kVectorLengthInBytes = 64 : i64, sym_name = "tcompute0_tcompute_phase0_vector_out_2000"} : () -> vector<32xbf16>
        "rail.for_loop"(%10) ( {
          %23:2 = "rail.accumulator"() {kInitValue = 0xFFF0000000000000 : f64, kNumStages = 1 : i64, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : () -> (vector<32xbf16>, vector<1x32xbf16>)
          "rail.for_loop"(%16) ( {
            %24 = "rail.pop"(%17) {kInstructionStageType = 1 : i64, kIsDataPathOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xbf16>) -> vector<32xbf16>
            %25 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 10 : si16} : () -> si16
            %26 = "rail.less_than"(%16, %25) {kInstructionStageType = 2 : i64, kIsBinaryOp = true, kIsBooleanOp = true, kIsDataPathOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64, si16) -> i1
            %27 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = -9.984000e+04 : bf16} : () -> bf16
            %28 = "rail.ifelse"(%26, %24, %27) {kInstructionStageType = 2 : i64, kIsDataPathOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i1, vector<32xbf16>, bf16) -> vector<32xbf16>
            %29 = "rail.max"(%28, %23#0) {kInstructionStageType = 2 : i64, kIsAccumulated = true, kIsArithmetic = true, kIsBinaryOp = true, kIsDataPathOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xbf16>, vector<32xbf16>) -> vector<32xbf16>
            "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:574:0"} : () -> ()
          }) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:574:0", type = none} : (i64) -> ()
          "rail.send"(%23#0, %18) {kInstructionStageType = 0 : i64, kIsDataPathOp = true, kOpRWPattern1 = "kWriteOperand", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xbf16>, vector<32xbf16>) -> ()
          "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:576:0"} : () -> ()
        }) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:576:0", type = none} : (i64) -> ()
        %19 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64) -> i1
        %20 = "rail.io.control_in"() {kCtxName = "phase0", kLanes = [], kPortName = "3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", sym_name = "tcompute0_tcompute_phase0_control_in_3000"} : () -> i1
        "rail.inbuf"(%20, %19) {kInit = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i1, i1) -> ()
        %21 = "rail.io.control_out"() {kCtxName = "phase0", kLanes = [], kPortName = "2000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", sym_name = "tcompute0_tcompute_phase0_control_out_2000"} : () -> i1
        %22 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64) -> i1
        "rail.send"(%22, %21) {kOpRWPattern1 = "kWriteOperand", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i1, i1) -> ()
        "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : () -> ()
      }) {kContextTableEntry = {kNetwork = 0 : i64}, kName = "phase0", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", sym_name = "phase0"} : () -> ()
      "rail.tcompute_context"() ( {
        %7 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 0 : i64} : () -> i64
        %8 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 1 : i64} : () -> i64
        %9 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 12 : i64} : () -> i64
        %10 = "rail.iterator"(%7, %8, %9) {Par = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64, i64, i64) -> i64
        %11 = "rail.io.vector_in"() {kCtxName = "phase1", kLanes = [], kPortName = "9000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", kVectorLengthInBytes = 64 : i64, sym_name = "tcompute0_tcompute_phase1_vector_in_9000"} : () -> vector<32xbf16>
        %12 = "rail.io.vector_in"() {kCtxName = "phase1", kLanes = [], kPortName = "6000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", kVectorLengthInBytes = 64 : i64, sym_name = "tcompute0_tcompute_phase1_vector_in_6000"} : () -> vector<32xbf16>
        %13 = "rail.io.vector_out"() {kCtxName = "phase1", kLanes = [], kPortName = "10000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", kVectorLengthInBytes = 64 : i64, sym_name = "tcompute0_tcompute_phase1_vector_out_10000"} : () -> vector<32xbf16>
        "rail.for_loop"(%10) ( {
          %18 = "rail.pop"(%12) {kInstructionStageType = 1 : i64, kIsDataPathOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xbf16>) -> vector<32xbf16>
          %19 = "rail.pop"(%11) {kInstructionStageType = 1 : i64, kIsDataPathOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xbf16>) -> vector<32xbf16>
          %20 = "rail.sub"(%19, %18) {kInstructionStageType = 2 : i64, kIsArithmetic = true, kIsBinaryOp = true, kIsDataPathOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xbf16>, vector<32xbf16>) -> vector<32xbf16>
          %21 = "rail.exp"(%20) {kInstructionStageType = 3 : i64, kIsDataPathOp = true, kIsTailComplexOp = true, kIsUnaryOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xbf16>) -> vector<32xbf16>
          "rail.send"(%21, %13) {kInstructionStageType = 0 : i64, kIsDataPathOp = true, kOpRWPattern1 = "kWriteOperand", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xbf16>, vector<32xbf16>) -> ()
          "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:613:0"} : () -> ()
        }) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:613:0", type = none} : (i64) -> ()
        %14 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64) -> i1
        %15 = "rail.io.control_in"() {kCtxName = "phase1", kLanes = [], kPortName = "3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", sym_name = "tcompute0_tcompute_phase1_control_in_3000"} : () -> i1
        "rail.inbuf"(%15, %14) {kInit = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i1, i1) -> ()
        %16 = "rail.io.control_out"() {kCtxName = "phase1", kLanes = [], kPortName = "2000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", sym_name = "tcompute0_tcompute_phase1_control_out_2000"} : () -> i1
        %17 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64) -> i1
        "rail.send"(%17, %16) {kOpRWPattern1 = "kWriteOperand", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i1, i1) -> ()
        "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : () -> ()
      }) {kContextTableEntry = {kNetwork = 0 : i64}, kName = "phase1", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", sym_name = "phase1"} : () -> ()
      "rail.tcompute_context"() ( {
        %7 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 0 : i64} : () -> i64
        %8 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 32 : i64} : () -> i64
        %9 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 1 : i64} : () -> i64
        %10 = "rail.iterator"(%7, %8, %9) {Par = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64, i64, i64) -> i64
        %11 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64) -> i1
        %12 = "rail.ctxdone"(%11) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i1) -> i1
        %13 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 0 : i64} : () -> i64
        %14 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 1 : i64} : () -> i64
        %15 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 12 : i64} : () -> i64
        %16 = "rail.iterator"(%13, %14, %15) {Par = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64, i64, i64) -> i64
        %17 = "rail.io.vector_in"() {kCtxName = "phase2", kLanes = [], kPortName = "12000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", kVectorLengthInBytes = 64 : i64, sym_name = "tcompute0_tcompute_phase2_vector_in_12000"} : () -> vector<32xbf16>
        %18 = "rail.io.vector_out"() {kCtxName = "phase2", kLanes = [], kPortName = "7000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", kVectorLengthInBytes = 64 : i64, sym_name = "tcompute0_tcompute_phase2_vector_out_7000"} : () -> vector<32xbf16>
        "rail.for_loop"(%10) ( {
          %23:2 = "rail.accumulator"() {kInitValue = 0.000000e+00 : f32, kNumStages = 1 : i64, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : () -> (vector<32xbf16>, vector<1x32xbf16>)
          "rail.for_loop"(%16) ( {
            %25 = "rail.pop"(%17) {kInstructionStageType = 1 : i64, kIsDataPathOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xbf16>) -> vector<32xbf16>
            %26 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 10 : si16} : () -> si16
            %27 = "rail.less_than"(%16, %26) {kInstructionStageType = 2 : i64, kIsBinaryOp = true, kIsBooleanOp = true, kIsDataPathOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64, si16) -> i1
            %28 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 0.000000e+00 : bf16} : () -> bf16
            %29 = "rail.ifelse"(%27, %25, %28) {kInstructionStageType = 2 : i64, kIsDataPathOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i1, vector<32xbf16>, bf16) -> vector<32xbf16>
            %30 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 1.000000e+00 : bf16} : () -> bf16
            "rail.tcompute_fma"(%29, %30, %23#0) {kInstructionStageType = 2 : i64, kIsArithmetic = true, kIsDataPathOp = true, kOpRWPattern2 = "kWriteOperand", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xbf16>, bf16, vector<32xbf16>) -> ()
            "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:643:0"} : () -> ()
          }) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:643:0", type = none} : (i64) -> ()
          %24 = "rail.recip"(%23#0) {kInstructionStageType = 3 : i64, kIsDataPathOp = true, kIsTailComplexOp = true, kIsUnaryOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xbf16>) -> vector<32xbf16>
          "rail.send"(%24, %18) {kInstructionStageType = 0 : i64, kIsDataPathOp = true, kOpRWPattern1 = "kWriteOperand", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xbf16>, vector<32xbf16>) -> ()
          "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:646:0"} : () -> ()
        }) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:646:0", type = none} : (i64) -> ()
        %19 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64) -> i1
        %20 = "rail.io.control_in"() {kCtxName = "phase2", kLanes = [], kPortName = "3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", sym_name = "tcompute0_tcompute_phase2_control_in_3000"} : () -> i1
        "rail.inbuf"(%20, %19) {kInit = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i1, i1) -> ()
        %21 = "rail.io.control_out"() {kCtxName = "phase2", kLanes = [], kPortName = "2000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", sym_name = "tcompute0_tcompute_phase2_control_out_2000"} : () -> i1
        %22 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64) -> i1
        "rail.send"(%22, %21) {kOpRWPattern1 = "kWriteOperand", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i1, i1) -> ()
        "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : () -> ()
      }) {kContextTableEntry = {kNetwork = 0 : i64}, kName = "phase2", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", sym_name = "phase2"} : () -> ()
      "rail.tcompute_context"() ( {
        %7 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 0 : i64} : () -> i64
        %8 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 32 : i64} : () -> i64
        %9 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 1 : i64} : () -> i64
        %10 = "rail.iterator"(%7, %8, %9) {Par = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64, i64, i64) -> i64
        %11 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64) -> i1
        %12 = "rail.ctxdone"(%11) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i1) -> i1
        %13 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 0 : i64} : () -> i64
        %14 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 1 : i64} : () -> i64
        %15 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 12 : i64} : () -> i64
        %16 = "rail.iterator"(%13, %14, %15) {Par = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64, i64, i64) -> i64
        %17 = "rail.io.vector_in"() {kCtxName = "phase3", kLanes = [], kPortName = "16000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", kVectorLengthInBytes = 64 : i64, sym_name = "tcompute0_tcompute_phase3_vector_in_16000"} : () -> vector<32xbf16>
        %18 = "rail.io.vector_in"() {kCtxName = "phase3", kLanes = [], kPortName = "17000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", kVectorLengthInBytes = 64 : i64, sym_name = "tcompute0_tcompute_phase3_vector_in_17000"} : () -> vector<32xbf16>
        %19 = "rail.io.vector_in"() {kCtxName = "phase3", kLanes = [], kPortName = "20000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", kVectorLengthInBytes = 64 : i64, sym_name = "tcompute0_tcompute_phase3_vector_in_20000"} : () -> vector<32xbf16>
        %20 = "rail.io.vector_in"() {kCtxName = "phase3", kLanes = [], kPortName = "21000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", kVectorLengthInBytes = 64 : i64, sym_name = "tcompute0_tcompute_phase3_vector_in_21000"} : () -> vector<32xsi16>
        %21 = "rail.io.vector_out"() {kCtxName = "phase3", kLanes = [], kPortName = "15000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", kVectorLengthInBytes = 64 : i64, sym_name = "tcompute0_tcompute_phase3_vector_out_15000"} : () -> vector<32xbf16>
        "rail.for_loop"(%10) ( {
          "rail.for_loop"(%16) ( {
            %26 = "rail.pop"(%17) {kInstructionStageType = 1 : i64, kIsDataPathOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xbf16>) -> vector<32xbf16>
            %27 = "rail.pop"(%18) {kInstructionStageType = 1 : i64, kIsDataPathOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xbf16>) -> vector<32xbf16>
            %28 = "rail.pop"(%19) {kInstructionStageType = 1 : i64, kIsDataPathOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xbf16>) -> vector<32xbf16>
            %29 = "rail.pop"(%20) {kInstructionStageType = 1 : i64, kIsDataPathOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xsi16>) -> vector<32xsi16>
            %30 = "rail.mul"(%26, %27) {kInstructionStageType = 2 : i64, kIsArithmetic = true, kIsBinaryOp = true, kIsDataPathOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xbf16>, vector<32xbf16>) -> vector<32xbf16>
            %31 = "rail.equal"(%29, %16) {kInstructionStageType = 2 : i64, kIsBinaryOp = true, kIsBooleanOp = true, kIsDataPathOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xsi16>, i64) -> vector<32xi1>
            %32 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 1.000000e+00 : bf16} : () -> bf16
            %33 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kValue = 0.000000e+00 : bf16} : () -> bf16
            %34 = "rail.ifelse"(%31, %32, %33) {kInstructionStageType = 2 : i64, kIsDataPathOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xi1>, bf16, bf16) -> bf16
            %35 = "rail.sub"(%30, %34) {kInstructionStageType = 2 : i64, kIsArithmetic = true, kIsBinaryOp = true, kIsDataPathOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xbf16>, bf16) -> vector<32xbf16>
            %36 = "rail.mul"(%35, %28) {kInstructionStageType = 2 : i64, kIsArithmetic = true, kIsBinaryOp = true, kIsDataPathOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xbf16>, vector<32xbf16>) -> vector<32xbf16>
            "rail.send"(%36, %21) {kInstructionStageType = 0 : i64, kIsDataPathOp = true, kOpRWPattern1 = "kWriteOperand", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (vector<32xbf16>, vector<32xbf16>) -> ()
            "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:698:0"} : () -> ()
          }) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:698:0", type = none} : (i64) -> ()
          "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:699:0"} : () -> ()
        }) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:699:0", type = none} : (i64) -> ()
        %22 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64) -> i1
        %23 = "rail.io.control_in"() {kCtxName = "phase3", kLanes = [], kPortName = "3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", sym_name = "tcompute0_tcompute_phase3_control_in_3000"} : () -> i1
        "rail.inbuf"(%23, %22) {kInit = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i1, i1) -> ()
        %24 = "rail.io.control_out"() {kCtxName = "phase3", kLanes = [], kPortName = "2000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kUnitName = "tcompute0", sym_name = "tcompute0_tcompute_phase3_control_out_2000"} : () -> i1
        %25 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i64) -> i1
        "rail.send"(%25, %24) {kOpRWPattern1 = "kWriteOperand", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : (i1, i1) -> ()
        "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : () -> ()
      }) {kContextTableEntry = {kNetwork = 1 : i64}, kName = "phase3", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", sym_name = "phase3"} : () -> ()
      "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"} : () -> ()
    }) {kDataFormat = "BF16", kName = "tcompute0", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", sym_name = "tcompute0"} : () -> ()
    module_terminator {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0"}
  }
  "rail.TConnect"() {kDst = @tcompute0::@tcompute0::@phase0::@tcompute0_tcompute_phase0_control_in_3000, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kSrc = @tcompute0::@tcompute0::@phase3::@tcompute0_tcompute_phase3_control_out_2000} : () -> ()
  "rail.TConnect"() {kDst = @tcompute0::@tcompute0::@phase1::@tcompute0_tcompute_phase1_control_in_3000, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kSrc = @tcompute0::@tcompute0::@phase0::@tcompute0_tcompute_phase0_control_out_2000} : () -> ()
  "rail.TConnect"() {kDst = @tcompute0::@tcompute0::@phase2::@tcompute0_tcompute_phase2_control_in_3000, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kSrc = @tcompute0::@tcompute0::@phase1::@tcompute0_tcompute_phase1_control_out_2000} : () -> ()
  "rail.TConnect"() {kDst = @tcompute0::@tcompute0::@phase3::@tcompute0_tcompute_phase3_control_in_3000, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1667:0", kSrc = @tcompute0::@tcompute0::@phase2::@tcompute0_tcompute_phase2_control_out_2000} : () -> ()
  module @tbuf_tmp0  {
    "rail.buffer"() ( {
      "rail.tbuffer_context"() ( {
        %7 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", kValue = 0 : i64} : () -> i64
        %8 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", kValue = 32 : i64} : () -> i64
        %9 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", kValue = 1 : i64} : () -> i64
        %10 = "rail.iterator"(%7, %8, %9) {Par = 1 : i32, kChainID = 0 : i64, kIterPos = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0"} : (i64, i64, i64) -> i64
        %11 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0"} : (i64) -> i1
        %12 = "rail.ctxdone"(%11) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0"} : (i1) -> i1
        "rail.iterchain"(%10) {kChainID = 0 : i64, kName = "addr_chain", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0"} : (i64) -> ()
        %13 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", kValue = 13 : i64} : () -> i64
        %14 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", kValue = true} : () -> i1
        %15 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", kValue = 0 : i64} : () -> i64
        %16 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", kValue = 0 : i64} : () -> i64
        "rail.addr"(%13, %10, %14, %15, %16) {kDim = 2 : i8, kMemOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", kVecDim = 1 : i64} : (i64, i64, i1, i64, i64) -> ()
        %17 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0"} : (i64) -> i1
        %18 = "rail.io.control_in"() {kCtxName = "phaseW0", kLanes = [], kPortName = "7000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", kUnitName = "tbuf_tmp0", sym_name = "7000"} : () -> i1
        "rail.inbuf"(%18, %17) {kInit = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0"} : (i1, i1) -> ()
        %19 = "rail.io.control_out"() {kCtxName = "phaseW0", kLanes = [], kPortName = "2000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "2000"} : () -> i1
        "rail.send"(%12, %19) {kOpRWPattern1 = "kWriteOperand", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        %20 = "rail.io.control_in"() {kCtxName = "phaseW0", kLanes = [], kName = "3000", kPortName = "3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "3000"} : () -> i1
        "rail.inbuf"(%20, %12) {kInit = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0"} : () -> ()
      }) {kConcurrencyGroup = 0 : i64, kContextType = "kRolled", kDisableFullStall = true, kName = "phaseW0", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", sym_name = "phaseW0"} : () -> ()
      "rail.tbuffer_context"() ( {
        %7 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = 0 : i64} : () -> i64
        %8 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = 1 : i64} : () -> i64
        %9 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = 12 : i64} : () -> i64
        %10 = "rail.iterator"(%7, %8, %9) {Par = 1 : i32, kChainID = 0 : i64, kIterPos = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i64, i64, i64) -> i64
        %11 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = 0 : i64} : () -> i64
        %12 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = 32 : i64} : () -> i64
        %13 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = 1 : i64} : () -> i64
        %14 = "rail.iterator"(%11, %12, %13) {Par = 1 : i32, kChainID = 0 : i64, kIterPos = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i64, i64, i64) -> i64
        %15 = "rail.ctrdone"(%14) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i64) -> i1
        %16 = "rail.ctxdone"(%15) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1) -> i1
        "rail.iterchain"(%14, %10) {kChainID = 0 : i64, kName = "addr_chain", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i64, i64) -> ()
        %17 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = 13 : i64} : () -> i64
        %18 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = true} : () -> i1
        %19 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = 0 : i64} : () -> i64
        %20 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = 0 : i64} : () -> i64
        "rail.addr"(%17, %14, %18, %19, %20) {kDim = 2 : i8, kMemOp = false, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kVecDim = 1 : i64} : (i64, i64, i1, i64, i64) -> ()
        %21 = "rail.ctrdone"(%14) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i64) -> i1
        %22 = "rail.io.control_in"() {kCtxName = "phaseRMax", kLanes = [], kPortName = "7000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "7000"} : () -> i1
        "rail.inbuf"(%22, %21) {kInit = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        %23 = "rail.ctrdone"(%14) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i64) -> i1
        %24 = "rail.io.control_in"() {kCtxName = "phaseRMax", kLanes = [], kPortName = "7001", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "7001"} : () -> i1
        "rail.inbuf"(%24, %23) {kInit = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        %25 = "rail.io.control_in"() {kCtxName = "phaseRMax", kLanes = [], kName = "3000", kPortName = "3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "3000"} : () -> i1
        "rail.inbuf"(%25, %16) {kInit = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        %26 = "rail.io.control_in"() {kCtxName = "phaseRMax", kLanes = [], kName = "3001", kPortName = "3001", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "3001"} : () -> i1
        "rail.inbuf"(%26, %16) {kInit = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        %27 = "rail.io.control_out"() {kCtxName = "phaseRMax", kLanes = [], kPortName = "2000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "2000"} : () -> i1
        "rail.send"(%16, %27) {kOpRWPattern1 = "kWriteOperand", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : () -> ()
      }) {kConcurrencyGroup = 0 : i64, kContextType = "kRolled", kDisableEmptyStall = true, kExplicitMemPort = 1 : i64, kName = "phaseRMax", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", sym_name = "phaseRMax"} : () -> ()
      "rail.tbuffer_context"() ( {
        %7 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:853:0", kValue = 0 : i64} : () -> i64
        %8 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:853:0", kValue = 1 : i64} : () -> i64
        %9 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:853:0", kValue = 1 : i64} : () -> i64
        %10 = "rail.iterator"(%7, %8, %9) {Par = 1 : i32, kChainID = 0 : i64, kIterPos = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:853:0"} : (i64, i64, i64) -> i64
        %11 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:853:0"} : (i64) -> i1
        %12 = "rail.ctxdone"(%11) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:853:0"} : (i1) -> i1
        "rail.iterchain"(%10) {kChainID = 0 : i64, kName = "addr_chain", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:853:0"} : (i64) -> ()
        %13 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:853:0", kValue = 0 : i64} : () -> i64
        %14 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:853:0", kValue = 0 : i64} : () -> i64
        %15 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:853:0", kValue = false} : () -> i1
        %16 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:853:0", kValue = 0 : i64} : () -> i64
        %17 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:853:0", kValue = 0 : i64} : () -> i64
        "rail.addr"(%13, %14, %15, %16, %17) {kDim = 2 : i8, kMemOp = false, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:853:0", kVecDim = 1 : i64} : (i64, i64, i1, i64, i64) -> ()
        %18 = "rail.io.control_in"() {kCtxName = "phase_rd_dummy", kLanes = [], kName = "3000", kPortName = "3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "3000"} : () -> i1
        "rail.inbuf"(%18, %12) {kInit = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        %19 = "rail.io.control_in"() {kCtxName = "phase_rd_dummy", kLanes = [], kName = "3001", kPortName = "3001", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "3001"} : () -> i1
        "rail.inbuf"(%19, %12) {kInit = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        %20 = "rail.io.control_out"() {kCtxName = "phase_rd_dummy", kLanes = [], kPortName = "2000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "2000"} : () -> i1
        "rail.send"(%12, %20) {kOpRWPattern1 = "kWriteOperand", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:853:0"} : () -> ()
      }) {kConcurrencyGroup = 0 : i64, kContextType = "kRolled", kDisableEmptyStall = true, kExplicitMemPort = 2 : i64, kName = "phase_rd_dummy", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:853:0", sym_name = "phase_rd_dummy"} : () -> ()
      "rail.tbuffer_context"() ( {
        %7 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0", kValue = 0 : i64} : () -> i64
        %8 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0", kValue = 1 : i64} : () -> i64
        %9 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0", kValue = 12 : i64} : () -> i64
        %10 = "rail.iterator"(%7, %8, %9) {Par = 1 : i32, kChainID = 0 : i64, kIterPos = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0"} : (i64, i64, i64) -> i64
        %11 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0", kValue = 0 : i64} : () -> i64
        %12 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0", kValue = 32 : i64} : () -> i64
        %13 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0", kValue = 1 : i64} : () -> i64
        %14 = "rail.iterator"(%11, %12, %13) {Par = 1 : i32, kChainID = 0 : i64, kIterPos = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0"} : (i64, i64, i64) -> i64
        %15 = "rail.ctrdone"(%14) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0"} : (i64) -> i1
        %16 = "rail.ctxdone"(%15) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0"} : (i1) -> i1
        "rail.iterchain"(%14, %10) {kChainID = 0 : i64, kName = "addr_chain", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0"} : (i64, i64) -> ()
        %17 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0", kValue = true} : () -> i1
        %18 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0", kValue = 0 : i64} : () -> i64
        %19 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0", kValue = 0 : i64} : () -> i64
        "rail.addr"(%10, %14, %17, %18, %19) {kDim = 2 : i8, kMemOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0", kVecDim = 1 : i64} : (i64, i64, i1, i64, i64) -> ()
        %20 = "rail.ctrdone"(%14) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0"} : (i64) -> i1
        %21 = "rail.io.control_in"() {kCtxName = "phaseW1", kLanes = [], kPortName = "7000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0", kUnitName = "tbuf_tmp0", sym_name = "7000"} : () -> i1
        "rail.inbuf"(%21, %20) {kInit = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0"} : (i1, i1) -> ()
        %22 = "rail.io.control_in"() {kCtxName = "phaseW1", kLanes = [], kName = "3000", kPortName = "3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "3000"} : () -> i1
        "rail.inbuf"(%22, %16) {kInit = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        %23 = "rail.io.control_out"() {kCtxName = "phaseW1", kLanes = [], kPortName = "2000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "2000"} : () -> i1
        "rail.send"(%16, %23) {kOpRWPattern1 = "kWriteOperand", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0"} : () -> ()
      }) {kConcurrencyGroup = 1 : i64, kContextType = "kRolled", kDisableFullStall = true, kName = "phaseW1", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:749:0", sym_name = "phaseW1"} : () -> ()
      "rail.tbuffer_context"() ( {
        %7 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kValue = 0 : i64} : () -> i64
        %8 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kValue = 32 : i64} : () -> i64
        %9 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kValue = 1 : i64} : () -> i64
        %10 = "rail.iterator"(%7, %8, %9) {Par = 1 : i32, kChainID = 0 : i64, kIterPos = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0"} : (i64, i64, i64) -> i64
        %11 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kValue = 0 : i64} : () -> i64
        %12 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kValue = 1 : i64} : () -> i64
        %13 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kValue = 12 : i64} : () -> i64
        %14 = "rail.iterator"(%11, %12, %13) {Par = 1 : i32, kChainID = 0 : i64, kIterPos = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0"} : (i64, i64, i64) -> i64
        %15 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0"} : (i64) -> i1
        %16 = "rail.ctxdone"(%15) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0"} : (i1) -> i1
        "rail.iterchain"(%10, %14) {kChainID = 0 : i64, kName = "addr_chain", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0"} : (i64, i64) -> ()
        %17 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kValue = true} : () -> i1
        %18 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kValue = 0 : i64} : () -> i64
        %19 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kValue = 0 : i64} : () -> i64
        "rail.addr"(%14, %10, %17, %18, %19) {kDim = 2 : i8, kMemOp = false, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kVecDim = 1 : i64} : (i64, i64, i1, i64, i64) -> ()
        %20 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0"} : (i64) -> i1
        %21 = "rail.io.control_in"() {kCtxName = "phaseRExp0", kLanes = [], kPortName = "7000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kUnitName = "tbuf_tmp0", sym_name = "7000"} : () -> i1
        "rail.inbuf"(%21, %20) {kInit = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0"} : (i1, i1) -> ()
        %22 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0"} : (i64) -> i1
        %23 = "rail.io.control_in"() {kCtxName = "phaseRExp0", kLanes = [], kPortName = "7001", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kUnitName = "tbuf_tmp0", sym_name = "7001"} : () -> i1
        "rail.inbuf"(%23, %22) {kInit = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0"} : (i1, i1) -> ()
        %24 = "rail.io.control_in"() {kCtxName = "phaseRExp0", kLanes = [], kName = "3000", kPortName = "3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "3000"} : () -> i1
        "rail.inbuf"(%24, %16) {kInit = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        %25 = "rail.io.control_in"() {kCtxName = "phaseRExp0", kLanes = [], kName = "3001", kPortName = "3001", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "3001"} : () -> i1
        "rail.inbuf"(%25, %16) {kInit = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        %26 = "rail.io.control_out"() {kCtxName = "phaseRExp0", kLanes = [], kPortName = "2000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "2000"} : () -> i1
        "rail.send"(%16, %26) {kOpRWPattern1 = "kWriteOperand", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0"} : () -> ()
      }) {kConcurrencyGroup = 1 : i64, kContextType = "kRolled", kDisableEmptyStall = true, kExplicitMemPort = 1 : i64, kName = "phaseRExp0", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", sym_name = "phaseRExp0"} : () -> ()
      "rail.tbuffer_context"() ( {
        %7 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", kValue = 0 : i64} : () -> i64
        %8 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", kValue = 32 : i64} : () -> i64
        %9 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", kValue = 1 : i64} : () -> i64
        %10 = "rail.iterator"(%7, %8, %9) {Par = 1 : i32, kChainID = 0 : i64, kIterPos = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0"} : (i64, i64, i64) -> i64
        %11 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0"} : (i64) -> i1
        %12 = "rail.ctxdone"(%11) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0"} : (i1) -> i1
        "rail.iterchain"(%10) {kChainID = 0 : i64, kName = "addr_chain", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0"} : (i64) -> ()
        %13 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", kValue = 12 : i64} : () -> i64
        %14 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", kValue = true} : () -> i1
        %15 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", kValue = 0 : i64} : () -> i64
        %16 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", kValue = 0 : i64} : () -> i64
        "rail.addr"(%13, %10, %14, %15, %16) {kDim = 2 : i8, kMemOp = true, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", kVecDim = 1 : i64} : (i64, i64, i1, i64, i64) -> ()
        %17 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0"} : (i64) -> i1
        %18 = "rail.io.control_in"() {kCtxName = "phaseW2", kLanes = [], kPortName = "7000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", kUnitName = "tbuf_tmp0", sym_name = "7000"} : () -> i1
        "rail.inbuf"(%18, %17) {kInit = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0"} : (i1, i1) -> ()
        %19 = "rail.io.control_in"() {kCtxName = "phaseW2", kLanes = [], kName = "3000", kPortName = "3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "3000"} : () -> i1
        "rail.inbuf"(%19, %12) {kInit = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        %20 = "rail.io.control_out"() {kCtxName = "phaseW2", kLanes = [], kPortName = "2000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "2000"} : () -> i1
        "rail.send"(%12, %20) {kOpRWPattern1 = "kWriteOperand", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0"} : () -> ()
      }) {kConcurrencyGroup = 2 : i64, kContextType = "kRolled", kDisableFullStall = true, kName = "phaseW2", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:716:0", sym_name = "phaseW2"} : () -> ()
      "rail.tbuffer_context"() ( {
        %7 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kValue = 0 : i64} : () -> i64
        %8 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kValue = 32 : i64} : () -> i64
        %9 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kValue = 1 : i64} : () -> i64
        %10 = "rail.iterator"(%7, %8, %9) {Par = 1 : i32, kChainID = 0 : i64, kIterPos = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0"} : (i64, i64, i64) -> i64
        %11 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kValue = 0 : i64} : () -> i64
        %12 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kValue = 1 : i64} : () -> i64
        %13 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kValue = 12 : i64} : () -> i64
        %14 = "rail.iterator"(%11, %12, %13) {Par = 1 : i32, kChainID = 0 : i64, kIterPos = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0"} : (i64, i64, i64) -> i64
        %15 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0"} : (i64) -> i1
        %16 = "rail.ctxdone"(%15) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0"} : (i1) -> i1
        "rail.iterchain"(%10, %14) {kChainID = 0 : i64, kName = "addr_chain", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0"} : (i64, i64) -> ()
        %17 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kValue = true} : () -> i1
        %18 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kValue = 0 : i64} : () -> i64
        %19 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kValue = 0 : i64} : () -> i64
        "rail.addr"(%14, %10, %17, %18, %19) {kDim = 2 : i8, kMemOp = false, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kVecDim = 1 : i64} : (i64, i64, i1, i64, i64) -> ()
        %20 = "rail.ctrdone"(%10) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0"} : (i64) -> i1
        %21 = "rail.io.control_in"() {kCtxName = "phaseRExp1", kLanes = [], kPortName = "7000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", kUnitName = "tbuf_tmp0", sym_name = "7000"} : () -> i1
        "rail.inbuf"(%21, %20) {kInit = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0"} : (i1, i1) -> ()
        %22 = "rail.io.control_out"() {kCtxName = "phaseRExp1", kLanes = [], kPortName = "2000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "2000"} : () -> i1
        "rail.send"(%16, %22) {kOpRWPattern1 = "kWriteOperand", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        %23 = "rail.io.control_in"() {kCtxName = "phaseRExp1", kLanes = [], kName = "3000", kPortName = "3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "3000"} : () -> i1
        "rail.inbuf"(%23, %16) {kInit = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        %24 = "rail.io.control_in"() {kCtxName = "phaseRExp1", kLanes = [], kName = "3001", kPortName = "3001", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "3001"} : () -> i1
        "rail.inbuf"(%24, %16) {kInit = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0"} : () -> ()
      }) {kConcurrencyGroup = 2 : i64, kContextType = "kRolled", kDisableEmptyStall = true, kExplicitMemPort = 1 : i64, kName = "phaseRExp1", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:816:0", sym_name = "phaseRExp1"} : () -> ()
      "rail.tbuffer_context"() ( {
        %7 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = 0 : i64} : () -> i64
        %8 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = 1 : i64} : () -> i64
        %9 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = 12 : i64} : () -> i64
        %10 = "rail.iterator"(%7, %8, %9) {Par = 1 : i32, kChainID = 0 : i64, kIterPos = 1 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i64, i64, i64) -> i64
        %11 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = 0 : i64} : () -> i64
        %12 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = 32 : i64} : () -> i64
        %13 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = 1 : i64} : () -> i64
        %14 = "rail.iterator"(%11, %12, %13) {Par = 1 : i32, kChainID = 0 : i64, kIterPos = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i64, i64, i64) -> i64
        %15 = "rail.ctrdone"(%14) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i64) -> i1
        %16 = "rail.ctxdone"(%15) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1) -> i1
        "rail.iterchain"(%14, %10) {kChainID = 0 : i64, kName = "addr_chain", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i64, i64) -> ()
        %17 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = 12 : i64} : () -> i64
        %18 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = true} : () -> i1
        %19 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = 0 : i64} : () -> i64
        %20 = "rail.const"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kValue = 0 : i64} : () -> i64
        "rail.addr"(%17, %14, %18, %19, %20) {kDim = 2 : i8, kMemOp = false, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kVecDim = 1 : i64} : (i64, i64, i1, i64, i64) -> ()
        %21 = "rail.ctrdone"(%14) {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i64) -> i1
        %22 = "rail.io.control_in"() {kCtxName = "phaseRSumRecip", kLanes = [], kPortName = "7000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "7000"} : () -> i1
        "rail.inbuf"(%22, %21) {kInit = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        %23 = "rail.io.control_out"() {kCtxName = "phaseRSumRecip", kLanes = [], kPortName = "2000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "2000"} : () -> i1
        "rail.send"(%16, %23) {kOpRWPattern1 = "kWriteOperand", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        %24 = "rail.io.control_in"() {kCtxName = "phaseRSumRecip", kLanes = [], kName = "3000", kPortName = "3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "3000"} : () -> i1
        "rail.inbuf"(%24, %16) {kInit = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        %25 = "rail.io.control_in"() {kCtxName = "phaseRSumRecip", kLanes = [], kName = "3001", kPortName = "3001", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", sym_name = "3001"} : () -> i1
        "rail.inbuf"(%25, %16) {kInit = 0 : i32, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : (i1, i1) -> ()
        "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0"} : () -> ()
      }) {kConcurrencyGroup = 2 : i64, kContextType = "kRolled", kDisableEmptyStall = true, kExplicitMemPort = 2 : i64, kName = "phaseRSumRecip", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", sym_name = "phaseRSumRecip"} : () -> ()
      "rail.terminator"() {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1558:0"} : () -> ()
    }) {kExplicitSwapDsts = ["phaseRSumRecip", "phaseRMax", "phaseW0"], kExplicitSwapSrcs = ["phaseRExp0", "phaseRExp1", "phaseW2"], kFIFOMode = false, kImplicitControl = false, kName = "tbuf_tmp0", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1558:0", params = {kDepth = 1 : i64, kLayout = {alignments = [[1, 64]], base_address = 0 : i64, dim_order = [0, 1], format = 8 : i64, shape = [14, 1], vector_transpose = 1 : i64}, kMinMaxCapacitySplit = true, kMinPmus = -1 : i64, kPacingWindow = -1 : i64, kSplitAlgorithm = 0 : i64}, sym_name = "tbuf_tmp0"} : () -> ()
    module_terminator {kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:1558:0"}
  }
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseW1::@"3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tbuf_tmp0::@tbuf_tmp0::@phaseW0::@"2000"} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseRMax::@"3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tbuf_tmp0::@tbuf_tmp0::@phaseW0::@"2000"} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseRMax::@"3001", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tbuf_tmp0::@tbuf_tmp0::@phaseRExp1::@"2000"} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phase_rd_dummy::@"3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tbuf_tmp0::@tbuf_tmp0::@phaseW0::@"2000"} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phase_rd_dummy::@"3001", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tbuf_tmp0::@tbuf_tmp0::@phaseRSumRecip::@"2000"} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseW2::@"3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tbuf_tmp0::@tbuf_tmp0::@phaseW1::@"2000"} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseRExp0::@"3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tbuf_tmp0::@tbuf_tmp0::@phaseW1::@"2000"} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseRExp0::@"3001", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tbuf_tmp0::@tbuf_tmp0::@phaseRMax::@"2000"} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseRExp1::@"3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tbuf_tmp0::@tbuf_tmp0::@phaseW2::@"2000"} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseRExp1::@"3001", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tbuf_tmp0::@tbuf_tmp0::@phaseRExp0::@"2000"} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseRSumRecip::@"3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tbuf_tmp0::@tbuf_tmp0::@phaseW2::@"2000"} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseRSumRecip::@"3001", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tbuf_tmp0::@tbuf_tmp0::@phase_rd_dummy::@"2000"} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseW0::@"3000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tbuf_tmp0::@tbuf_tmp0::@phaseW2::@"2000"} : () -> ()
  %0 = "rail.io.vector_in"() {kCtxName = "phaseW0", kLanes = [], kPortName = "8", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", kVectorLengthInBytes = 64 : i64, sym_name = "tbuf_tmp0_tbuffer_phaseW0_vector_in_8"} : () -> vector<32xbf16>
  "rail.TConnect"() {kDst = @tbuf_tmp0_tbuffer_phaseW0_vector_in_8, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tcompute0::@tcompute0::@phase0::@tcompute0_tcompute_phase0_vector_out_2000} : () -> ()
  %1 = "rail.io.vector_out"() {kCtxName = "phaseRMax", kLanes = [], kPortName = "1001", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", kVectorLengthInBytes = 64 : i64, sym_name = "tbuf_tmp0_tbuffer_phaseRMax_vector_out_1001"} : () -> vector<32xbf16>
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseRMax::@"7000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tcompute0::@tcompute0::@phase0::@tcompute0_tcompute_phase0_control_out_2000} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseRMax::@"7001", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tcompute0::@tcompute0::@phase3::@tcompute0_tcompute_phase3_control_out_2000} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseW1::@"7000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tcompute0::@tcompute0::@phase3::@tcompute0_tcompute_phase3_control_out_2000} : () -> ()
  "rail.TConnect"() {kDst = @tcompute0::@tcompute0::@phase1::@tcompute0_tcompute_phase1_vector_in_6000, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tbuf_tmp0_tbuffer_phaseRMax_vector_out_1001} : () -> ()
  %2 = "rail.io.vector_in"() {kCtxName = "phaseW1", kLanes = [], kPortName = "8", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", kVectorLengthInBytes = 64 : i64, sym_name = "tbuf_tmp0_tbuffer_phaseW1_vector_in_8"} : () -> vector<32xbf16>
  "rail.TConnect"() {kDst = @tbuf_tmp0_tbuffer_phaseW1_vector_in_8, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tcompute0::@tcompute0::@phase1::@tcompute0_tcompute_phase1_vector_out_10000} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseRExp0::@"7000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tcompute0::@tcompute0::@phase1::@tcompute0_tcompute_phase1_control_out_2000} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseRExp0::@"7001", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tcompute0::@tcompute0::@phase3::@tcompute0_tcompute_phase3_control_out_2000} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseW2::@"7000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tcompute0::@tcompute0::@phase1::@tcompute0_tcompute_phase1_control_out_2000} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseRSumRecip::@"7000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tcompute0::@tcompute0::@phase2::@tcompute0_tcompute_phase2_control_out_2000} : () -> ()
  %3 = "rail.io.vector_out"() {kCtxName = "phaseRExp0", kLanes = [], kPortName = "1001", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", kVectorLengthInBytes = 64 : i64, sym_name = "tbuf_tmp0_tbuffer_phaseRExp0_vector_out_1001"} : () -> vector<32xbf16>
  "rail.TConnect"() {kDst = @tcompute0::@tcompute0::@phase2::@tcompute0_tcompute_phase2_vector_in_12000, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tbuf_tmp0_tbuffer_phaseRExp0_vector_out_1001} : () -> ()
  %4 = "rail.io.vector_in"() {kCtxName = "phaseW2", kLanes = [], kPortName = "8", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", kVectorLengthInBytes = 64 : i64, sym_name = "tbuf_tmp0_tbuffer_phaseW2_vector_in_8"} : () -> vector<32xbf16>
  "rail.TConnect"() {kDst = @tbuf_tmp0_tbuffer_phaseW2_vector_in_8, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tcompute0::@tcompute0::@phase2::@tcompute0_tcompute_phase2_vector_out_7000} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseRExp1::@"7000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tcompute0::@tcompute0::@phase2::@tcompute0_tcompute_phase2_control_out_2000} : () -> ()
  %5 = "rail.io.vector_out"() {kCtxName = "phaseRExp1", kLanes = [], kPortName = "1001", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", kVectorLengthInBytes = 64 : i64, sym_name = "tbuf_tmp0_tbuffer_phaseRExp1_vector_out_1001"} : () -> vector<32xbf16>
  "rail.TConnect"() {kDst = @tcompute0::@tcompute0::@phase3::@tcompute0_tcompute_phase3_vector_in_16000, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tbuf_tmp0_tbuffer_phaseRExp1_vector_out_1001} : () -> ()
  %6 = "rail.io.vector_out"() {kCtxName = "phaseRSumRecip", kLanes = [], kPortName = "1001", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kUnitName = "tbuf_tmp0", kVectorLengthInBytes = 64 : i64, sym_name = "tbuf_tmp0_tbuffer_phaseRSumRecip_vector_out_1001"} : () -> vector<32xbf16>
  "rail.TConnect"() {kDst = @tcompute0::@tcompute0::@phase3::@tcompute0_tcompute_phase3_vector_in_17000, kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tbuf_tmp0_tbuffer_phaseRSumRecip_vector_out_1001} : () -> ()
  "rail.TConnect"() {kDst = @tbuf_tmp0::@tbuf_tmp0::@phaseW0::@"7000", kSourceContext = "software/compiler/apps/rail/cross_entropy_grad/template/src/RAILCrossEntropyGrad.cpp:877:0", kSrc = @tcompute0::@tcompute0::@phase3::@tcompute0_tcompute_phase3_control_out_2000} : () -> ()
  module_terminator {kSourceContext = "LogregTorchSamba.cpp:220:0"}
}