#!/bin/bash -l
#COBALT -n 2
#COBALT -t 0:20:00 
#COBALT -A GRACE
#COBALT -q full-node
#COBALT --attrs filesystems=home
#COBALT -o ./logs/testpt_out
#COBALT -e ./logs/testpt_err

#submisstion script for running pytorch_mnist with DDP

echo "Running Cobalt Job $COBALT_JOBID."

module load conda
conda activate
# module load nccl/nccl-v2.12.12-1_CUDA11.4

N_NODES=$(cat $COBALT_NODEFILE | wc -l)
RANKS_PER_NODE=8
let N_RANKS=${RANKS_PER_NODE}*${N_NODES}

echo "Current Directory: "
pwd

# --hostfile ${COBALT_NODEFILE} 
# NCCL_DEBUG=INFO mpirun -n $N_RANKS --map-by node python ../scripts/test/test_ddp_mpic.py
mpirun -n $N_RANKS --hostfile ${COBALT_NODEFILE} --npernode 8 -x PATH -x LD_LIBRARY_PATH -x PYTHONSTARTUP -x PYTHONUSERBASE python ../scripts/test/test_ddp_mpic.py