from .timeseries_prediction.deepDMD import DeepDMDReferenceImplementation
from .timeseries_prediction.proxyDeepDMD import TFOptimizedSGPU
from .timeseries_prediction.proxyDeepDMDMGPU import TFOptimizedEncoder, TFOptimizedModelTrainer