module @schedule_0_2 attributes {plasma.kBitfileType = 7 : i64, plasma.kVerbose = false}  {
  plasma.Segment @segment_3() attributes {kChipId = 0 : i64, kIsInputOnly = false, kMemoryLocation = 2 : i64, kPoolId = 0 : i64, kSegmentId = 0 : i64, kSegmentSize = 23618 : i64}  {
    plasma.symbol.Dram @ptconvlstm__lstm_layer__lstm__hidden__output() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<1x60x64xbf16:RVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = false, kMemoryLocation = 2 : i64, kName = "ptconvlstm__lstm_layer__lstm__hidden__output", kOffset = 0 : i64, kSymbolAnnotation = 0 : i64} {}
    plasma.symbol.Dram @ptconvlstm__lstm_layer__lstm__cell__output() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<1x60x64xbf16:RVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = false, kMemoryLocation = 2 : i64, kName = "ptconvlstm__lstm_layer__lstm__cell__output", kOffset = 7680 : i64, kSymbolAnnotation = 0 : i64} {}
    plasma.symbol.Dram @ptconvlstm__view__outputs__0() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<1x30x136xbf16:RVRM>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = false, kMemoryLocation = 2 : i64, kName = "ptconvlstm__view__outputs__0", kOffset = 15360 : i64, kSymbolAnnotation = 0 : i64} {}
    plasma.symbol.Dram @ptconvlstm__criterion__mseloss__outputs__0() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<1xbf16:RVRM>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = false, kMemoryLocation = 2 : i64, kName = "ptconvlstm__criterion__mseloss__outputs__0", kOffset = 23552 : i64, kSymbolAnnotation = 0 : i64} {}
  }
  plasma.Segment @segment_2() attributes {kChipId = 0 : i64, kIsInputOnly = true, kMemoryLocation = 2 : i64, kPoolId = 0 : i64, kSegmentId = 1 : i64, kSegmentSize = 15428 : i64}  {
    plasma.symbol.Dram @lstm_operand_1() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<1x60x64xbf16:RVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = true, kIsUserFacing = true, kIsWeight = false, kMemoryLocation = 2 : i64, kName = "lstm_operand_1", kOffset = 0 : i64, kSymbolAnnotation = 0 : i64} {}
    plasma.symbol.Dram @lstm_operand_0() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<1x60x64xbf16:RVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = true, kIsUserFacing = true, kIsWeight = false, kMemoryLocation = 2 : i64, kName = "lstm_operand_0", kOffset = 7680 : i64, kSymbolAnnotation = 0 : i64} {}
    plasma.symbol.Dram @ptconvlstm__lstm_layer__lstm__outputs__0_slice_1() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<1xi32:RVRM>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = true, kIsUserFacing = true, kIsWeight = false, kMemoryLocation = 2 : i64, kName = "ptconvlstm__lstm_layer__lstm__outputs__0_slice_1", kOffset = 15360 : i64, kSymbolAnnotation = 0 : i64} {}
  }
  plasma.Segment @segment_1() attributes {kChipId = 0 : i64, kIsInputOnly = false, kMemoryLocation = 0 : i64, kPoolId = 0 : i64, kSegmentId = 2 : i64, kSegmentSize = 2029632 : i64}  {
    plasma.symbol.Dram @group_23() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<256xbf16:RVRM>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = false, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "group_23", kOffset = 0 : i64, kSymbolAnnotation = 0 : i64}  {
      plasma.symbol.Dram @ptconvlstm__lstm_layer__bias_hh_l0() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4x64x1xbf16:CVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = true, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__bias_hh_l0", kOffset = 0 : i64, kSymbolAnnotation = 0 : i64} {}
    }
    plasma.symbol.Dram @group_24() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<256xbf16:RVRM>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = false, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "group_24", kOffset = 512 : i64, kSymbolAnnotation = 0 : i64}  {
      plasma.symbol.Dram @ptconvlstm__lstm_layer__bias_ih_l0() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4x64x1xbf16:CVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = true, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__bias_ih_l0", kOffset = 0 : i64, kSymbolAnnotation = 0 : i64} {}
    }
    plasma.symbol.Dram @group_25() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<16384xbf16:RVRM>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = false, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "group_25", kOffset = 1024 : i64, kSymbolAnnotation = 0 : i64}  {
      plasma.symbol.Dram @ptconvlstm__lstm_layer__weight_hh_l0() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4x64x64xbf16:CVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = true, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__weight_hh_l0", kOffset = 0 : i64, kSymbolAnnotation = 0 : i64} {}
    }
    plasma.symbol.Dram @group_26() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<34816xbf16:RVRM>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = false, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "group_26", kOffset = 33792 : i64, kSymbolAnnotation = 0 : i64}  {
      plasma.symbol.Dram @ptconvlstm__lstm_layer__weight_ih_l0() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4x64x136xbf16:CVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = true, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__weight_ih_l0", kOffset = 0 : i64, kSymbolAnnotation = 0 : i64} {}
    }
    plasma.symbol.Dram @group_27() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4096xbf16:RVRM>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = false, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "group_27", kOffset = 103424 : i64, kSymbolAnnotation = 0 : i64}  {
      plasma.symbol.Dram @ptconvlstm__dense_layer__bias() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4080x1xbf16:CVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = true, kMemoryLocation = 0 : i64, kName = "ptconvlstm__dense_layer__bias", kOffset = 0 : i64, kSymbolAnnotation = 0 : i64} {}
    }
    plasma.symbol.Dram @group_4() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<262144xbf16:RVRM>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = false, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "group_4", kOffset = 111616 : i64, kSymbolAnnotation = 0 : i64}  {
      plasma.symbol.Dram @ptconvlstm__dense_layer__weight() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4080x64xbf16:CVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = true, kMemoryLocation = 0 : i64, kName = "ptconvlstm__dense_layer__weight", kOffset = 0 : i64, kSymbolAnnotation = 0 : i64} {}
    }
    plasma.symbol.Dram @ptconvlstm__criterion__mseloss__outputs__0__grad() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<1xbf16:RVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "ptconvlstm__criterion__mseloss__outputs__0__grad", kOffset = 635904 : i64, kSymbolAnnotation = 0 : i64} {}
    plasma.symbol.Dram @ptconvlstm__view__outputs__0__grad() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<1x30x136xbf16:RVRM>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "ptconvlstm__view__outputs__0__grad", kOffset = 636416 : i64, kSymbolAnnotation = 0 : i64} {}
    plasma.symbol.Dram @ptconvlstm__lstm_layer__lstm__cell__output__grad() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<1x60x64xbf16:RVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__lstm__cell__output__grad", kOffset = 644608 : i64, kSymbolAnnotation = 0 : i64} {}
    plasma.symbol.Dram @ptconvlstm__lstm_layer__lstm__hidden__output__grad() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<1x60x64xbf16:RVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__lstm__hidden__output__grad", kOffset = 652288 : i64, kSymbolAnnotation = 0 : i64} {}
    plasma.symbol.Dram @group_28() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<262144xbf16:RVRM>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = false, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "group_28", kOffset = 659968 : i64, kSymbolAnnotation = 0 : i64}  {
      plasma.symbol.Dram @ptconvlstm__dense_layer__weight__sgd0__momentum() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4080x64xbf16:CVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = true, kMemoryLocation = 0 : i64, kName = "ptconvlstm__dense_layer__weight__sgd0__momentum", kOffset = 0 : i64, kSymbolAnnotation = 0 : i64} {}
    }
    plasma.symbol.Dram @group_29() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<55808xbf16:RVRM>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = false, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "group_29", kOffset = 1184256 : i64, kSymbolAnnotation = 0 : i64}  {
      plasma.symbol.Dram @ptconvlstm__dense_layer__bias__sgd0__momentum() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4080x1xbf16:CVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = true, kMemoryLocation = 0 : i64, kName = "ptconvlstm__dense_layer__bias__sgd0__momentum", kOffset = 0 : i64, kSymbolAnnotation = 0 : i64} {}
      plasma.symbol.Dram @ptconvlstm__lstm_layer__weight_ih_l0__sgd0__momentum() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4x64x136xbf16:CVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = true, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__weight_ih_l0__sgd0__momentum", kOffset = 8192 : i64, kSymbolAnnotation = 0 : i64} {}
      plasma.symbol.Dram @ptconvlstm__lstm_layer__weight_hh_l0__sgd0__momentum() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4x64x64xbf16:CVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = true, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__weight_hh_l0__sgd0__momentum", kOffset = 77824 : i64, kSymbolAnnotation = 0 : i64} {}
      plasma.symbol.Dram @ptconvlstm__lstm_layer__bias_ih_l0__sgd0__momentum() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4x64x1xbf16:CVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = true, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__bias_ih_l0__sgd0__momentum", kOffset = 110592 : i64, kSymbolAnnotation = 0 : i64} {}
      plasma.symbol.Dram @ptconvlstm__lstm_layer__bias_hh_l0__sgd0__momentum() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4x64x1xbf16:CVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = true, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__bias_hh_l0__sgd0__momentum", kOffset = 111104 : i64, kSymbolAnnotation = 0 : i64} {}
    }
    plasma.symbol.Dram @ptconvlstm__lstm_layer__lstm3_used_by_ptconvlstm__lstm_layer__lstm_bwd() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<1x64x60xbf16:CVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = false, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__lstm3_used_by_ptconvlstm__lstm_layer__lstm_bwd", kOffset = 1295872 : i64, kSymbolAnnotation = 0 : i64} {}
    plasma.symbol.Dram @ptconvlstm__lstm_layer__lstm4_used_by_ptconvlstm__lstm_layer__lstm_bwd() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<1x64x60xbf16:CVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = false, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__lstm4_used_by_ptconvlstm__lstm_layer__lstm_bwd", kOffset = 1303552 : i64, kSymbolAnnotation = 0 : i64} {}
    plasma.symbol.Dram @ptconvlstm__lstm_layer__lstm5_used_by_ptconvlstm__lstm_layer__lstm_bwd() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<1x64x60xbf16:CVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = false, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__lstm5_used_by_ptconvlstm__lstm_layer__lstm_bwd", kOffset = 1311232 : i64, kSymbolAnnotation = 0 : i64} {}
    plasma.symbol.Dram @ptconvlstm__lstm_layer__lstm6_used_by_ptconvlstm__lstm_layer__lstm_bwd() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<1x64x60xbf16:CVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = false, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__lstm6_used_by_ptconvlstm__lstm_layer__lstm_bwd", kOffset = 1318912 : i64, kSymbolAnnotation = 0 : i64} {}
    plasma.symbol.Dram @ptconvlstm__lstm_layer__lstm7_used_by_ptconvlstm__lstm_layer__lstm_bwd() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<1x64x60xbf16:CVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = false, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__lstm7_used_by_ptconvlstm__lstm_layer__lstm_bwd", kOffset = 1326592 : i64, kSymbolAnnotation = 0 : i64} {}
    plasma.symbol.Dram @ptconvlstm__lstm_layer__lstm_meta_outputs0_used_by_ptconvlstm__lstm_layer__lstm_shifted_outputs() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<2x60x64xbf16:RVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = false, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__lstm_meta_outputs0_used_by_ptconvlstm__lstm_layer__lstm_shifted_outputs", kOffset = 1334272 : i64, kSymbolAnnotation = 0 : i64} {}
    plasma.symbol.Dram @group_30() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<262144xbf16:RVRM>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = false, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "group_30", kOffset = 1349632 : i64, kSymbolAnnotation = 0 : i64}  {
      plasma.symbol.Dram @ptconvlstm__dense_layer__weight__grad() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4080x64xbf16:CVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "ptconvlstm__dense_layer__weight__grad", kOffset = 0 : i64, kSymbolAnnotation = 0 : i64} {}
    }
    plasma.symbol.Dram @group_31() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4096xbf16:RVRM>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = false, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "group_31", kOffset = 1873920 : i64, kSymbolAnnotation = 0 : i64}  {
      plasma.symbol.Dram @ptconvlstm__dense_layer__bias__grad() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4080x1xbf16:CVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "ptconvlstm__dense_layer__bias__grad", kOffset = 0 : i64, kSymbolAnnotation = 0 : i64} {}
    }
    plasma.symbol.Dram @ptconvlstm__lstm_layer__weight_hh_l0__grad() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4x64x64xbf16:RVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__weight_hh_l0__grad", kOffset = 1882112 : i64, kSymbolAnnotation = 0 : i64} {}
    plasma.symbol.Dram @ptconvlstm__lstm_layer__weight_ih_l0__grad() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4x64x136xbf16:RVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__weight_ih_l0__grad", kOffset = 1914880 : i64, kSymbolAnnotation = 0 : i64} {}
    plasma.symbol.Dram @ptconvlstm__lstm_layer__bias_hh_l0__grad() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4x64x1xbf16:RVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__bias_hh_l0__grad", kOffset = 1996800 : i64, kSymbolAnnotation = 0 : i64} {}
    plasma.symbol.Dram @ptconvlstm__lstm_layer__bias_ih_l0__grad() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<4x64x1xbf16:RVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = false, kIsUserFacing = true, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "ptconvlstm__lstm_layer__bias_ih_l0__grad", kOffset = 2013184 : i64, kSymbolAnnotation = 0 : i64} {}
  }
  plasma.Segment @segment_0() attributes {kChipId = 0 : i64, kIsInputOnly = true, kMemoryLocation = 0 : i64, kPoolId = 0 : i64, kSegmentId = 3 : i64, kSegmentSize = 27680 : i64}  {
    plasma.symbol.Dram @inp_window() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<1x60x136xbf16:RVRM:64>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = true, kIsUserFacing = true, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "inp_window", kOffset = 0 : i64, kSymbolAnnotation = 0 : i64} {}
    plasma.symbol.Dram @out_window() attributes {kChipId = 0 : i64, kDeviceLayout = !plasma.TL<1x30x136xbf16:RVRM>, kHasInitFunc = false, kIsAdminMode = false, kIsInputOnly = true, kIsUserFacing = true, kIsWeight = false, kMemoryLocation = 0 : i64, kName = "out_window", kOffset = 19456 : i64, kSymbolAnnotation = 0 : i64} {}
  }
  func @main() {
    %0:2 = "plasma.MemoryAddr"() {kTargetSymbol = @lstm_operand_0} : () -> (!plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,W>)
    %1:2 = "plasma.MemoryAddr"() {kTargetSymbol = @lstm_operand_1} : () -> (!plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,W>)
    %2:2 = "plasma.MemoryAddr"() {kTargetSymbol = @ptconvlstm__lstm_layer__lstm__outputs__0_slice_1} : () -> (!plasma.TLMemRef<!plasma.TL<1xi32:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<1xi32:RVRM>,0,W>)
    %3:2 = "plasma.MemoryAddr"() {kTargetSymbol = @group_4} : () -> (!plasma.TLMemRef<!plasma.TL<262144xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<262144xbf16:RVRM>,0,W>)
    %4:2 = "plasma.MemoryAddr"() {kTargetSymbol = @group_27} : () -> (!plasma.TLMemRef<!plasma.TL<4096xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<4096xbf16:RVRM>,0,W>)
    %5:2 = "plasma.MemoryAddr"() {kTargetSymbol = @inp_window} : () -> (!plasma.TLMemRef<!plasma.TL<1x60x136xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x60x136xbf16:RVRM:64>,0,W>)
    %6:2 = "plasma.MemoryAddr"() {kTargetSymbol = @group_26} : () -> (!plasma.TLMemRef<!plasma.TL<34816xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<34816xbf16:RVRM>,0,W>)
    %7:2 = "plasma.MemoryAddr"() {kTargetSymbol = @group_25} : () -> (!plasma.TLMemRef<!plasma.TL<16384xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<16384xbf16:RVRM>,0,W>)
    %8:2 = "plasma.MemoryAddr"() {kTargetSymbol = @group_24} : () -> (!plasma.TLMemRef<!plasma.TL<256xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<256xbf16:RVRM>,0,W>)
    %9:2 = "plasma.MemoryAddr"() {kTargetSymbol = @group_23} : () -> (!plasma.TLMemRef<!plasma.TL<256xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<256xbf16:RVRM>,0,W>)
    %10:2 = "plasma.MemoryAddr"() {kTargetSymbol = @out_window} : () -> (!plasma.TLMemRef<!plasma.TL<1x30x136xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<1x30x136xbf16:RVRM>,0,W>)
    %11:2 = "plasma.MemoryAddr"() {kTargetSymbol = @ptconvlstm__lstm_layer__lstm_meta_outputs0_used_by_ptconvlstm__lstm_layer__lstm_shifted_outputs} : () -> (!plasma.TLMemRef<!plasma.TL<2x60x64xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<2x60x64xbf16:RVRM:64>,0,W>)
    %12:2 = "plasma.MemoryAddr"() {kTargetSymbol = @ptconvlstm__lstm_layer__lstm3_used_by_ptconvlstm__lstm_layer__lstm_bwd} : () -> (!plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,W>)
    %13:2 = "plasma.MemoryAddr"() {kTargetSymbol = @ptconvlstm__lstm_layer__lstm4_used_by_ptconvlstm__lstm_layer__lstm_bwd} : () -> (!plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,W>)
    %14:2 = "plasma.MemoryAddr"() {kTargetSymbol = @ptconvlstm__lstm_layer__lstm5_used_by_ptconvlstm__lstm_layer__lstm_bwd} : () -> (!plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,W>)
    %15:2 = "plasma.MemoryAddr"() {kTargetSymbol = @ptconvlstm__lstm_layer__lstm6_used_by_ptconvlstm__lstm_layer__lstm_bwd} : () -> (!plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,W>)
    %16:2 = "plasma.MemoryAddr"() {kTargetSymbol = @ptconvlstm__lstm_layer__lstm7_used_by_ptconvlstm__lstm_layer__lstm_bwd} : () -> (!plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,W>)
    %17:2 = "plasma.MemoryAddr"() {kTargetSymbol = @ptconvlstm__view__outputs__0} : () -> (!plasma.TLMemRef<!plasma.TL<1x30x136xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<1x30x136xbf16:RVRM>,0,W>)
    %18:2 = "plasma.MemoryAddr"() {kTargetSymbol = @ptconvlstm__lstm_layer__lstm__hidden__output} : () -> (!plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,W>)
    %19:2 = "plasma.MemoryAddr"() {kTargetSymbol = @ptconvlstm__lstm_layer__lstm__cell__output} : () -> (!plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,W>)
    %20:2 = "plasma.MemoryAddr"() {kTargetSymbol = @ptconvlstm__criterion__mseloss__outputs__0} : () -> (!plasma.TLMemRef<!plasma.TL<1xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<1xbf16:RVRM>,0,W>)
    "plasma.CallSection"(%0#0, %1#0, %2#0, %3#0, %4#0, %5#0, %6#0, %7#0, %8#0, %9#0, %10#0, %11#1, %12#1, %13#1, %14#1, %15#1, %16#1, %17#1, %18#1, %19#1, %11#1, %20#1) {kSection = @s0} : (!plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1xi32:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<262144xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<4096xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<1x60x136xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<34816xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<16384xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<256xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<256xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<1x30x136xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<2x60x64xbf16:RVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<1x30x136xbf16:RVRM>,0,W>, !plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<2x60x64xbf16:RVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<1xbf16:RVRM>,0,W>) -> ()
    %21:2 = "plasma.MemoryAddr"() {kTargetSymbol = @ptconvlstm__criterion__mseloss__outputs__0__grad} : () -> (!plasma.TLMemRef<!plasma.TL<1xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1xbf16:RVRM:64>,0,W>)
    %22:2 = "plasma.MemoryAddr"() {kTargetSymbol = @ptconvlstm__lstm_layer__lstm__hidden__output__grad} : () -> (!plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,W>)
    %23:2 = "plasma.MemoryAddr"() {kTargetSymbol = @ptconvlstm__lstm_layer__lstm__cell__output__grad} : () -> (!plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,W>)
    %24:2 = "plasma.MemoryAddr"() {kTargetSymbol = @ptconvlstm__view__outputs__0__grad} : () -> (!plasma.TLMemRef<!plasma.TL<1x30x136xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<1x30x136xbf16:RVRM>,0,W>)
    %25:2 = "plasma.MemoryAddr"() {kTargetSymbol = @group_4::@ptconvlstm__dense_layer__weight} : () -> (!plasma.TLMemRef<!plasma.TL<4080x64xbf16:CVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<4080x64xbf16:CVRM:64>,0,W>)
    %26:2 = "plasma.MemoryAddr"() {kTargetSymbol = @group_30::@ptconvlstm__dense_layer__weight__grad} : () -> (!plasma.TLMemRef<!plasma.TL<4080x64xbf16:CVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<4080x64xbf16:CVRM:64>,0,W>)
    %27:2 = "plasma.MemoryAddr"() {kTargetSymbol = @group_31::@ptconvlstm__dense_layer__bias__grad} : () -> (!plasma.TLMemRef<!plasma.TL<4080x1xbf16:CVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<4080x1xbf16:CVRM:64>,0,W>)
    %28:2 = "plasma.MemoryAddr"() {kTargetSymbol = @ptconvlstm__lstm_layer__weight_hh_l0__grad} : () -> (!plasma.TLMemRef<!plasma.TL<4x64x64xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<4x64x64xbf16:RVRM:64>,0,W>)
    %29:2 = "plasma.MemoryAddr"() {kTargetSymbol = @ptconvlstm__lstm_layer__weight_ih_l0__grad} : () -> (!plasma.TLMemRef<!plasma.TL<4x64x136xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<4x64x136xbf16:RVRM:64>,0,W>)
    %30:2 = "plasma.MemoryAddr"() {kTargetSymbol = @ptconvlstm__lstm_layer__bias_ih_l0__grad} : () -> (!plasma.TLMemRef<!plasma.TL<4x64x1xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<4x64x1xbf16:RVRM:64>,0,W>)
    %31:2 = "plasma.MemoryAddr"() {kTargetSymbol = @ptconvlstm__lstm_layer__bias_hh_l0__grad} : () -> (!plasma.TLMemRef<!plasma.TL<4x64x1xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<4x64x1xbf16:RVRM:64>,0,W>)
    "plasma.CallSection"(%0#0, %1#0, %2#0, %3#0, %4#0, %21#0, %22#0, %23#0, %24#0, %5#0, %6#0, %7#0, %8#0, %9#0, %10#0, %25#0, %5#0, %12#0, %13#0, %14#0, %15#0, %16#0, %11#0, %26#1, %27#1, %28#1, %28#1, %28#1, %28#1, %29#1, %29#1, %29#1, %29#1, %30#1, %30#1, %30#1, %30#1, %31#1, %31#1, %31#1, %31#1) {kSection = @s1} : (!plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1xi32:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<262144xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<4096xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<1xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x60x64xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x30x136xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<1x60x136xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<34816xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<16384xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<256xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<256xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<1x30x136xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<4080x64xbf16:CVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x60x136xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<1x64x60xbf16:CVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<2x60x64xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<4080x64xbf16:CVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<4080x1xbf16:CVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<4x64x64xbf16:RVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<4x64x64xbf16:RVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<4x64x64xbf16:RVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<4x64x64xbf16:RVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<4x64x136xbf16:RVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<4x64x136xbf16:RVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<4x64x136xbf16:RVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<4x64x136xbf16:RVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<4x64x1xbf16:RVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<4x64x1xbf16:RVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<4x64x1xbf16:RVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<4x64x1xbf16:RVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<4x64x1xbf16:RVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<4x64x1xbf16:RVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<4x64x1xbf16:RVRM:64>,0,W>, !plasma.TLMemRef<!plasma.TL<4x64x1xbf16:RVRM:64>,0,W>) -> ()
    %32:2 = "plasma.MemoryAddr"() {kTargetSymbol = @group_30} : () -> (!plasma.TLMemRef<!plasma.TL<262144xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<262144xbf16:RVRM>,0,W>)
    %33:2 = "plasma.MemoryAddr"() {kTargetSymbol = @group_28} : () -> (!plasma.TLMemRef<!plasma.TL<262144xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<262144xbf16:RVRM>,0,W>)
    %34:2 = "plasma.MemoryAddr"() {kTargetSymbol = @group_31} : () -> (!plasma.TLMemRef<!plasma.TL<4096xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<4096xbf16:RVRM>,0,W>)
    %35:2 = "plasma.MemoryAddr"() {kTargetSymbol = @group_29} : () -> (!plasma.TLMemRef<!plasma.TL<55808xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<55808xbf16:RVRM>,0,W>)
    "plasma.CallSection"(%3#0, %32#0, %33#0, %4#0, %34#0, %35#0, %6#0, %29#0, %7#0, %28#0, %8#0, %30#0, %9#0, %31#0, %3#1, %33#1, %4#1, %35#1, %6#1, %7#1, %8#1, %9#1) {kSection = @s2} : (!plasma.TLMemRef<!plasma.TL<262144xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<262144xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<262144xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<4096xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<4096xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<55808xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<34816xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<4x64x136xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<16384xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<4x64x64xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<256xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<4x64x1xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<256xbf16:RVRM>,0,R>, !plasma.TLMemRef<!plasma.TL<4x64x1xbf16:RVRM:64>,0,R>, !plasma.TLMemRef<!plasma.TL<262144xbf16:RVRM>,0,W>, !plasma.TLMemRef<!plasma.TL<262144xbf16:RVRM>,0,W>, !plasma.TLMemRef<!plasma.TL<4096xbf16:RVRM>,0,W>, !plasma.TLMemRef<!plasma.TL<55808xbf16:RVRM>,0,W>, !plasma.TLMemRef<!plasma.TL<34816xbf16:RVRM>,0,W>, !plasma.TLMemRef<!plasma.TL<16384xbf16:RVRM>,0,W>, !plasma.TLMemRef<!plasma.TL<256xbf16:RVRM>,0,W>, !plasma.TLMemRef<!plasma.TL<256xbf16:RVRM>,0,W>) -> ()
    "plasma.Terminator"() : () -> ()
  }
}
